# Generated by Django 5.0.7 on 2024-07-23 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Esp32Control',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('area', models.FloatField()),
                ('bateria', models.FloatField()),
                ('descarga', models.FloatField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Esp32Humedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('bateria', models.FloatField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Raspberry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('ruta', models.CharField(blank=True, default='', max_length=100)),
                ('area', models.FloatField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('bateria', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LecturaEsp32',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('humedad_suelo', models.FloatField()),
                ('et0', models.FloatField()),
                ('ruta', models.CharField(default='', max_length=100)),
                ('idEsp32', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.esp32humedad')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('semana', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('kc', models.FloatField()),
                ('volumen_ha', models.FloatField()),
                ('idEsp32', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.esp32control')),
            ],
        ),
        migrations.CreateModel(
            name='LecturaRaspberry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('humedad_ambiente', models.FloatField()),
                ('temperatura_ambiente', models.FloatField()),
                ('radiacion_solar', models.FloatField()),
                ('presion_atmosferica', models.FloatField()),
                ('velocidad_viento', models.FloatField()),
                ('et0', models.FloatField()),
                ('ruta', models.CharField(max_length=100)),
                ('idRaspberry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.raspberry')),
            ],
        ),
        migrations.AddField(
            model_name='esp32humedad',
            name='idRaspberry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.raspberry'),
        ),
        migrations.AddField(
            model_name='esp32control',
            name='idRaspberry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.raspberry'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idRaspberry',
            field=models.ManyToManyField(to='api.raspberry'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol'),
        ),
    ]
