# Generated by Django 5.0.7 on 2024-07-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioLecturaEsp32',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('humedad_suelo', models.FloatField()),
                ('et0', models.FloatField()),
                ('idEsp32', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiarioLecturaRaspberry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('humedad_ambiente', models.FloatField()),
                ('temperatura_ambiente', models.FloatField()),
                ('radiacion_solar', models.FloatField()),
                ('presion_atmosferica', models.FloatField()),
                ('velocidad_viento', models.FloatField()),
                ('et0', models.FloatField()),
                ('ruta', models.CharField(default='', max_length=100)),
                ('idRaspberry', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MesLecturaEsp32',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('humedad_suelo', models.FloatField()),
                ('et0', models.FloatField()),
                ('idEsp32', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MesLecturaRaspberry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('humedad_ambiente', models.FloatField()),
                ('temperatura_ambiente', models.FloatField()),
                ('radiacion_solar', models.FloatField()),
                ('presion_atmosferica', models.FloatField()),
                ('velocidad_viento', models.FloatField()),
                ('et0', models.FloatField()),
                ('idRaspberry', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SemanaLecturaRaspberry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semana', models.IntegerField()),
                ('humedad_ambiente', models.FloatField()),
                ('temperatura_ambiente', models.FloatField()),
                ('radiacion_solar', models.FloatField()),
                ('presion_atmosferica', models.FloatField()),
                ('velocidad_viento', models.FloatField()),
                ('et0', models.FloatField()),
                ('idRaspberry', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UltimaEsp32',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField()),
                ('humedad_suelo', models.FloatField()),
                ('idEsp32', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UltimaLecturaRaspberry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('humedad_ambiente', models.FloatField()),
                ('temperatura_ambiente', models.FloatField()),
                ('radiacion_solar', models.FloatField()),
                ('presion_atmosferica', models.FloatField()),
                ('velocidad_viento', models.FloatField()),
                ('et0', models.FloatField()),
                ('ruta', models.CharField(default='', max_length=100)),
                ('idRaspberry', models.IntegerField()),
            ],
        ),
    ]
