# Generated by Django 5.0.7 on 2024-07-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_diariolecturaesp32_diariolecturaraspberry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diariolecturaesp32',
            name='et0',
        ),
    ]
