# Generated by Django 5.0.7 on 2024-07-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_diariolecturaesp32_et0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturaesp32',
            name='et0',
        ),
        migrations.RemoveField(
            model_name='lecturaesp32',
            name='ruta',
        ),
    ]
