# Generated by Django 5.0.7 on 2024-07-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_lecturaesp32_et0_remove_lecturaesp32_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meslecturaesp32',
            name='et0',
        ),
    ]
