# Generated by Django 5.0.7 on 2024-07-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_meslecturaesp32_et0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meslecturaraspberry',
            name='fecha',
        ),
    ]
