# Generated by Django 5.0.7 on 2024-07-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_meslecturaraspberry_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='meslecturaraspberry',
            name='mes',
            field=models.IntegerField(default=0),
        ),
    ]
