# Generated by Django 5.0.7 on 2024-07-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meslecturaraspberry_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meslecturaesp32',
            name='fecha',
        ),
    ]
