# Generated by Django 5.0.7 on 2024-07-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_meslecturaesp32_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='meslecturaesp32',
            name='mes',
            field=models.IntegerField(default=0),
        ),
    ]
