# Generated by Django 5.0.7 on 2024-07-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_meslecturaesp32_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultimaesp32',
            name='codigo',
        ),
    ]
