# Generated by Django 5.0.7 on 2024-07-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_ultimaesp32_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SieteDiasAnterioresLecturaEsp32',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('humedad_suelo', models.FloatField()),
                ('idEsp32', models.IntegerField()),
            ],
        ),
    ]
