# Generated by Django 5.0.7 on 2024-07-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sietediasanterioreslecturaesp32'),
    ]

    operations = [
        migrations.AddField(
            model_name='diariolecturaesp32',
            name='dia',
            field=models.IntegerField(default=0),
        ),
    ]
