# Generated by Django 5.0.7 on 2024-07-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_diariolecturaesp32_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sietediasanterioreslecturaesp32',
            name='dia',
            field=models.IntegerField(default=0),
        ),
    ]
