# Generated by Django 5.0.7 on 2024-07-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_sietediasanterioreslecturaesp32_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SieteDiasAnterioresLecturaRaspberry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('dia', models.IntegerField(default=0)),
                ('humedad_ambiente', models.FloatField()),
                ('temperatura_ambiente', models.FloatField()),
                ('radiacion_solar', models.FloatField()),
                ('presion_atmosferica', models.FloatField()),
                ('velocidad_viento', models.FloatField()),
                ('et0', models.FloatField()),
                ('ruta', models.CharField(default='', max_length=100)),
                ('idRaspberry', models.IntegerField()),
            ],
        ),
    ]
