# Generated by Django 5.0.7 on 2024-07-30 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sietediasanterioreslecturaraspberry'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32control',
            name='cc',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='esp32control',
            name='pmp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
