# Generated by Django 5.0.7 on 2024-07-31 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_esp32control_cc_esp32control_pmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp32control',
            name='cc',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='esp32control',
            name='pmp',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
